---
- name: Create prometheus directory
  file:
    path: /opt/prometheus
    owner: reddiprasadyendluri
    state: directory
    mode: 0775
- name: ensure permissions are correct
  file:
    path: "{{ item }}"
    owner: reddiprasadyendluri
    group: reddiprasadyendluri
    state: directory
    mode: 0775
  with_items: "{{ prometheus_home }}"
- name: Install prometheus exporter
  get_url:
    url: "{{ prometheus.prometheus_package_url }}"
    dest: "{{ prometheus_home }}"
    mode: 0755
    remote_src: yes
