---
all:
  vars:
    ansible_connection: ssh
    ansible_user: reddiprasadyendluri
    ansible_become: true
    ansible_ssh_pass: xyzabce
    #ansible_ssh_private_key_file: /Users/reddiprasadyendluri/.ssh/id_rsa
    jmxexporter_jar_url: "https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.15.0/jmx_prometheus_javaagent-0.15.0.jar"
    jmxexporter_enabled: false
    install_java: true
    prometheus_home: /opt/prometheus
    ansible_os_family: Ubuntu
    jmx_prometheus_javaagent: jmx_prometheus_javaagent
    
preflight:
  hosts:
    localhost #include all hosts
